# Generated by Django 3.2.6 on 2021-08-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_server_author_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_claim', models.CharField(max_length=128, unique=True)),
                ('data_claim', models.JSONField(blank=True, null=True)),
                ('status_claim', models.CharField(choices=[('Complete', 'Complete'), ('Error', 'Error'), ('Running', 'Running'), ('Wait', 'Wait'), ('Stop', 'Stop')], default='Wait', max_length=100, null=True)),
                ('created_claim', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_claim', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name_plural': '01. Danh sách yêu cầu',
            },
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
