# Generated by Django 3.2.6 on 2021-08-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210820_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='note_claim',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
