# Generated by Django 3.2.6 on 2021-08-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_claim_note_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='company_claim',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
