# Generated by Django 3.2.6 on 2021-08-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='author_server',
        ),
    ]
